#!/bin/bash
# Script to fix permissions of accounts
# Written by: Vanessa Vasile 5/13/10
# Written by: laudarch 10/16/22
# http://thecpaneladmin.com
#
# ./fixperms user1 user2 user3
#
# You can also run a server-wide loop like this:
#
# for i in `ls -A /var/cpanel/users` ; do ./fixperms $i ; done

if [ "$#" -lt "1" ];then
  echo "Must specify user"
  #echo "./fixperms user1 [user2] [user3] ..."
  #echo "You can also run a server-wide loop like this:"
  #echo "for i in `ls -A /var/cpanel/users` ; do ./fixperms $i ; done"
  exit;
fi

USER=$@

for user in $USER
do

  HOMEDIR=$(egrep "^${user}:" /etc/passwd | cut -d: -f6)

  if [ ! -f /var/cpanel/users/$user ]; then
    echo "$user user file missing, likely an invalid user"
  elif [ "$HOMEDIR" == "" ];then
    echo "Couldn't determine home directory for $user"
  else
    echo "Setting ownership for user $user"
    chown -R $user:$user $HOMEDIR
    chmod 711 $HOMEDIR
    chown $user:nobody $HOMEDIR/public_html $HOMEDIR/.htpasswds
    chown $user:mail $HOMEDIR/etc $HOMEDIR/etc/*/shadow $HOMEDIR/etc/*/passwd

    echo "Setting permissions for user $USER"

    find $HOMEDIR -type f -print0 | xargs -0 chmod 0644
    find $HOMEDIR -type d -print0 | xargs -0 chmod 0755
    find $HOMEDIR -type d -name cgi-bin -print0 | xargs -0 chmod 0755

    #find $HOMEDIR -type f -exec chmod 644 {} ; echo
    #find $HOMEDIR -type d -exec chmod 755 {} ; echo
    #find $HOMEDIR -type d -name cgi-bin -exec chmod 755 {} ; echo
    #find $HOMEDIR -type f -name "*.pl" -o -name "*.perl" -exec chmod 755 {} ; echo
  fi

done

chmod 750 $HOMEDIR/public_html

if [ -d "$HOMEDIR/.cagefs" ]; then
  chmod 775 $HOMEDIR/.cagefs
  chmod 700 $HOMEDIR/.cagefs/tmp
  chmod 700 $HOMEDIR/.cagefs/var
  chmod 777 $HOMEDIR/.cagefs/cache
  chmod 777 $HOMEDIR/.cagefs/run
fi
